### ISSUE TITLE
issue in the first example for buildPalindrome

### ISSUE THREAD

**Issue by MShel** [Shawn-Ng/algorithms#3]
Hey Shawn so in this file:
https://github.com/Shawn-Ng/algorithms/blob/master/codefights/buildPalindrome/test.py
in the first implementation you are missing condition in case we have passed the premade Palindrome(aka abba will become abbabba)

**Comment by shawnngtq** [comment]
Thanks for pointing out. I have added the missing condition to check if input is palindrome before appending more characters to the input.
